Aic 1 create chevron variants
cezarmocanu/ai-coach pull request #3
Opened 2024-03-28 15:32 UTC by malexa21

I am having problems with introducing in Storybook.

2024-03-28 18:23 UTC, CezarMocanu-aily requested changes

2024-03-28 18:23 UTC, CezarMocanu-aily commented on src/shared/components/atoms/ChevronDown/ChevronDown.stories.ts
> +  component: ChevronDownVariant,
The component should be `ChevronDown`. A variant is a type of that component. Please test the storybook by running 
```
npm run storybook
```

You should be able to go trough all the chevron types

2024-03-28 18:23 UTC, CezarMocanu-aily commented on src/shared/components/atoms/ChevronDown/ChevronDown.stories.ts
> +} satisfies Meta<typeof ChevronDownVariant>;
type should be ChevronDown

2024-03-28 18:23 UTC, CezarMocanu-aily commented on src/shared/components/atoms/ChevronDown/ChevronDown.stories.ts
> +export const ChevronDown: Story = {};
Here you need to export one for each variant so you should export 

```
export const Outlined: Story = {
    args: {
       variant: ChevronDownVariant.outline,
    }
}

export const Solid: Story = {...}
export const Mini: Story = {...}
export const Micro: Story = {...}
```

2024-03-28 18:27 UTC, cezarmocanu requested changes
Please fix comments

2024-03-31 08:40 UTC, cezarmocanu approved these changes

2024-03-31 08:41 UTC, merged